name: CI pipeline
on:
  pus:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          if [-f requirements.txt]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi


      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip pipenv
          if [-f Pipfile]; then
            pipenv install --dev --skip-lock
          fi

      - name: Run unit tests
        working-directory: "tests"
        run: |
          if [-f Pipfile ]; then
            pipenv run pytest unit_tests/
          fi

      - name: Lint
        working-directory: .
        run: |
          if [-f Pipfile]; then
            pipenv run pylint --recursive=y src
          fi
